=== JuliaQUBO/QUBOTools.jl/src/library/format/bqpjson/bqpjson.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Binary Quadratic Program Schema",
    "type": "object",
    "required": [
        "version",
        "id",
        "variable_ids",
        "variable_domain",
        "scale",
        "offset",
        "linear_terms",
        "quadratic_terms",
        "metadata"
    ],
    "properties": {
        "version": {
            "type": "string",
            "enum": [
                "1.0.0"
            ]
        },
        "id": {
            "type": "integer",
            "minimum": 0
        },
        "metadata": {
            "type": "object",
            "properties": {
                "dw_url": {
                    "type": "string"
                },
                "dw_solver_name": {
                    "type": "string"
                },
                "dw_chip_id": {
                    "type": "string"
                },
                "chimera_cell_size": {
                    "type": "integer",
                    "minimum": 0
                },
                "chimera_degree": {
                    "type": "integer",
                    "minimum": 0
                },
                "generated": {
                    "type": "string"
                },
                "dwig_generator": {
                    "type": "string"
                },
                "synthesis": {
                    "oneOf": [
                        {
                            "$ref": "#/definitions/wishart_synthesis_metadata"
                        },
                        {
                            "$ref": "#/definitions/generic_synthesis_metadata"
                        }
                    ]
                }
            }
        },
        "variable_ids": {
            "type": "array",
            "items": {
                "type": "integer",
                "minimum": 0
            }
        },
        "variable_domain": {
            "type": "string",
            "enum": [
                "spin",
                "boolean"
            ]
        },
        "scale": {
            "type": "number"
        },
        "offset": {
            "type": "number"
        },
        "linear_terms": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "id",
                    "coeff"
                ],
                "properties": {
                    "id": {
                        "type": "integer",
                        "minimum": 0
                    },
                    "coeff": {
                        "type": "number"
                    }
                }
            }
        },
        "quadratic_terms": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "id_head",
                    "id_tail",
                    "coeff"
                ],
                "properties": {
                    "id_head": {
                        "type": "integer",
                        "minimum": 0
                    },
                    "id_tail": {
                        "type": "integer",
                        "minimum": 0
                    },
                    "coeff": {
                        "type": "number"
                    }
                }
            }
        },
        "description": {
            "type": "string"
        },
        "solutions": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "id",
                    "assignment"
                ],
                "properties": {
                    "id": {
                        "type": "integer",
                        "minimum": 0
                    },
                    "description": {
                        "type": "string"
                    },
                    "evaluation": {
                        "type": "number"
                    },
                    "assignment": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": [
                                "id",
                                "value"
                            ],
                            "properties": {
                                "id": {
                                    "type": "integer",
                                    "minimum": 0
                                },
                                "value": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "generic_synthesis_metadata": {
            "type": "object",
            "required": [
                "model",
                "parameters"
            ],
            "properties": {
                "model": {
                    "type": "string",
                    "not": {
                        "enum": [
                            "Wishart"
                        ]
                    }
                },
                "parameters": {
                    "type": "object"
                }
            }
        },
        "wishart_synthesis_metadata": {
            "type": "object",
            "required": [
                "model",
                "parameters"
            ],
            "properties": {
                "model": {
                    "type": "string",
                    "enum": [
                        "Wishart"
                    ]
                },
                "parameters": {
                    "type": "object",
                    "required": [
                        "n",
                        "m"
                    ],
                    "properties": {
                        "n": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "m": {
                            "type": "integer",
                            "minimum": 0
                        }
                    }
                }
            }
        }
    }
}

=== JuliaQUBO/QUBOTools.jl/test/data/000.b.json
{
    "description": "simple model with linear_terms",
    "id": 0,
    "linear_terms": [
        {
            "coeff": 1.3,
            "id": 2
        },
        {
            "coeff": -0.7,
            "id": 6
        }
    ],
    "metadata": {},
    "offset": 0.0,
    "quadratic_terms": [],
    "scale": 1.0,
    "variable_domain": "boolean",
    "variable_ids": [
        2,
        4,
        6
    ],
    "version": "1.0.0"
}

=== JuliaQUBO/QUBOTools.jl/test/data/02b.json
{
  "description":"simple model with quadratic_terms and metadata",
  "id": 0,
  "linear_terms": [
    {"coeff":  1.3, "id": 2},
    {"coeff": -0.7, "id": 6}
  ],
  "metadata": {
    "some_key_1":"any value",
    "some_key_2":0.3,
    "some_key_3":null,
    "some_key_4":["one", 2, 3.7, null]
  },
  "offset": 1.23,
  "quadratic_terms": [
    {"coeff": -0.2, "id_head": 4, "id_tail": 2},
    {"coeff":  1.5, "id_head": 6, "id_tail": 2}
  ],
  "scale": 2.7,
  "variable_domain": "spin",
  "variable_ids": [2,4,6],
  "version": "1.0.0"
}
